project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "Global River Chemistry"
  repo-url: https://github.com/global-river-chem/global-river-chem.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left: 
      - text: "Products"
        href: products.qmd
    right: 
      - text: "People"
        href: people.qmd
      - icon: github
        href: https://github.com/global-river-chem/global-river-chem.github.io
  page-footer: 
    center: "Copyright &copy; 2026, River Si Big Data Team"
    background: secondary

format:
  html:
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    theme:
      light: themes/lwg-light.scss
      dark: themes/lwg-dark.scss
    mainfont: Open Sans